name: lion
channels:
  - astra-toolbox
  - pkgs/main
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - astra-toolbox=2.4.0=py312hf5d4436_0
  - blas=1.0=openblas
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.11.4=h06a4308_0
  - cuda-cudart=12.8.90=hbdd6827_0
  - cuda-cudart_linux-64=12.8.90=hd1a145a_0
  - cuda-version=12.8=h30beaf8_3
  - expat=2.7.3=h3385a95_0
  - ld_impl_linux-64=2.44=h153f514_2
  - libastra=2.4.0=cuda_12.8_0
  - libcufft=11.3.3.83=hbdd6827_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libnsl=2.0.0=h5eee18b_0
  - libopenblas=0.3.30=h46f56fc_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - ncurses=6.5=h7934f7d_0
  - numpy=2.3.4=py312h816806e_1
  - openssl=3.0.18=hd6dcaed_0
  - pip=25.2=pyhc872135_1
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.12.12=hd17a9e1_1
  - readline=8.3=hc2a1206_0
  - scipy=1.16.3=py312he2bc341_0
  - setuptools=80.9.0=py312h06a4308_0
  - sqlite=3.51.0=h2a70700_0
  - tk=8.6.15=h54e0aa7_0
  - tzdata=2025b=h04d1e81_0
  - wheel=0.45.1=py312h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - pip:
    - GitPython==3.1.45
    - ImageIO==2.37.2
    - Jinja2==3.1.6
    - LION==0.0.1
    - MarkupSafe==3.0.3
    - PyWavelets==1.9.0
    - PyYAML==6.0.3
    - SQLAlchemy==2.0.44
    - aiohappyeyeballs==2.6.1
    - aiohttp==3.13.2
    - aiosignal==1.4.0
    - annotated-types==0.7.0
    - astropy==7.1.1
    - astropy-iers-data==0.2025.11.3.0.38.37
    - attrs==25.4.0
    - certifi==2025.10.5
    - charset-normalizer==3.4.4
    - click==8.3.0
    - contourpy==1.3.3
    - cycler==0.12.1
    - deepinv==0.3.6
    - diskcache==5.6.3
    - einops==0.8.1
    - filelock==3.20.0
    - fonttools==4.60.1
    - frozenlist==1.8.0
    - fsspec==2025.10.0
    - girder-client==3.2.11
    - gitdb==4.0.12
    - greenlet==3.2.4
    - h5py==3.15.1
    - idna==3.11
    - kiwisolver==1.4.9
    - kornia==0.8.2
    - kornia_rs==0.1.10
    - lazy_loader==0.4
    - lightning==2.5.6
    - lightning-utilities==0.15.2
    - matplotlib==3.10.7
    - mpmath==1.3.0
    - multidict==6.7.0
    - natsort==8.4.0
    - networkx==3.5
    - numpy==2.2.6
    - nvidia-cublas-cu12==12.8.4.1
    - nvidia-cuda-cupti-cu12==12.8.90
    - nvidia-cuda-nvrtc-cu12==12.8.93
    - nvidia-cuda-runtime-cu12==12.8.90
    - nvidia-cudnn-cu12==9.10.2.21
    - nvidia-cufft-cu12==11.3.3.83
    - nvidia-cufile-cu12==1.13.1.3
    - nvidia-curand-cu12==10.3.9.90
    - nvidia-cusolver-cu12==11.7.3.90
    - nvidia-cusparse-cu12==12.5.8.93
    - nvidia-cusparselt-cu12==0.7.1
    - nvidia-nccl-cu12==2.27.5
    - nvidia-nvjitlink-cu12==12.8.93
    - nvidia-nvshmem-cu12==3.3.20
    - nvidia-nvtx-cu12==12.8.90
    - opencv-python==4.12.0.88
    - packaging==25.0
    - pandas==2.3.3
    - pillow==12.0.0
    - platformdirs==4.5.0
    - propcache==0.4.1
    - protobuf==6.33.0
    - pydantic==2.12.4
    - pydantic_core==2.41.5
    - pydicom==3.0.1
    - pyerfa==2.0.1.5
    - pylidc==0.2.3
    - pyparsing==3.2.5
    - python-dateutil==2.9.0.post0
    - pytorch-lightning==2.5.6
    - pytz==2025.2
    - requests==2.32.5
    - requests-toolbelt==1.0.0
    - scikit-image==0.25.2
    - sentry-sdk==2.43.0
    - six==1.17.0
    - smmap==5.0.2
    - spyrit==3.0.2
    - sympy==1.14.0
    - tifffile==2025.10.16
    - tomosipo==0.7.0
    - torch==2.9.0
    - torchdiffeq==0.2.5
    - torchmetrics==1.8.2
    - torchvision==0.24.0
    - tqdm==4.67.1
    - triton==3.5.0
    - ts_algorithms==0.1.0
    - typing-inspection==0.4.2
    - typing_extensions==4.15.0
    - tzdata==2025.2
    - urllib3==2.5.0
    - wandb==0.22.3
    - wget==3.2
    - yarl==1.22.0
